apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: orion-mcp 
  name: orion-mcp 
  namespace: ${BUGZOOKA_NAMESPACE}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: orion-mcp 
      app.kubernetes.io/name: orion-mcp 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: orion-mcp
        app.kubernetes.io/name: orion-mcp 
    spec:
      containers:
      - image: quay.io/jtaleric/orion-mcp
        imagePullPolicy: Always
        name: mcp 
        env:
        - name: ES_SERVER 
          value: ${ES_SERVER}
        ports:
        - containerPort: 3030
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
