apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugzooka
  namespace: ${BUGZOOKA_NAMESPACE}
  labels:
    app: ${BUGZOOKA_NAMESPACE}
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "bugzooka:latest",
            "namespace": "${BUGZOOKA_NAMESPACE}"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"bugzooka\")].image"
        }
      ]
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${BUGZOOKA_NAMESPACE}
      deployment: bugzooka
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${BUGZOOKA_NAMESPACE}
        deployment: bugzooka
    spec:
      containers:
        - name: bugzooka
          securityContext:
            allowPrivilegeEscalation: false
          image: bugzooka:latest
          imagePullPolicy: IfNotPresent
          args: []
          env:
            - name: CI
              value: "prow"
            - name: ENABLE_SOCKET_MODE
              value: "false"
          envFrom:
            - secretRef:
                name: bugzooka-env
          volumeMounts:
            - name: prompt
              mountPath: /app/prompt.json
              subPath: prompt.json
            - name: mcp-config
              mountPath: /app/mcp_config.json
              subPath: mcp_config.json
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              memory: "2Gi"
      volumes:
        - name: prompt
          configMap:
            name: bugzooka-prompt
            items:
              - key: prompt.json
                path: prompt.json
        - name: mcp-config
          configMap:
            name: bugzooka-mcp-config
            items:
              - key: mcp_config.json
                path: mcp_config.json
