apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${BUGZOOKA_NAMESPACE}

resources:
  - namespace.yaml
  - secret-quay.yaml
  - serviceaccount-patch.yaml
  - imagestream.yaml
  - configmap-prompts.yaml
  - configmap-mcp-config.yaml
  - deployment.yaml
  - deployment-orion-mcp.yaml
  - service-orion-mcp.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: bugzooka-env
    namespace: ${BUGZOOKA_NAMESPACE}
    envs:
      - .env
