name: Image Push
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
  release:
    types: [published]

jobs:
  image-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    steps:
      - uses: actions/checkout@v2

      - name: Decide Image Name
        id: set-image
        run: |
          if [[ "${{ github.event_name }}" == "release" && "${{ github.event.action }}" == "published" ]]; then
            echo "image=bugzooka" >> $GITHUB_OUTPUT
          else
            echo "image=bugzooka-dev" >> $GITHUB_OUTPUT
          fi

      - name: Build BugZooka Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ steps.set-image.outputs.image }}
          context: .
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push BugZooka Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: quay.io/redhat-performance
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
